"""empty message

Revision ID: 24a4049c0097
Revises: 610725c58e19
Create Date: 2023-01-25 23:21:11.287755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a4049c0097'
down_revision = '610725c58e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
